Version 4
SymbolType BLOCK
RECTANGLE Normal 96 -96 0 0
TEXT 22 -47 Left 2 MUX
PIN 0 -80 LEFT 8
PINATTR PinName a
PINATTR SpiceOrder 1
PIN 0 -48 LEFT 8
PINATTR PinName b
PINATTR SpiceOrder 2
PIN 0 -16 LEFT 8
PINATTR PinName s
PINATTR SpiceOrder 3
PIN 96 -48 RIGHT 8
PINATTR PinName o
PINATTR SpiceOrder 4
PIN 48 -96 TOP 8
PINATTR PinName Vdd
PINATTR SpiceOrder 5
PIN 48 0 BOTTOM 8
PINATTR PinName Vss
PINATTR SpiceOrder 6
